FROM nginx:1.24

WORKDIR /etc/nginx

RUN mkdir -p /etc/nginx/ssl


COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY ssl/serveur-bundle.crt /etc/nginx/ssl/certificat.crt
COPY ssl/serveur.key /etc/nginx/ssl/certificat.key

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
