version: "3.9"

services:
  nginx:
    image: nginx-crypto
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
